name: alpine-docker-images

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 4 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Alpine Latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-alpine:latest
          context: ./alpine
          file: ./alpine/Dockerfile
      - name: Image digestlatest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
      - name: Build and push Alpine Edge
        id: docker_build_edge
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-alpine:edge
          context: ./alpine-edge
          file: ./alpine-edge/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_edge.outputs.digest }}
      - name: Build and push Alpine 3
        id: docker_build_3
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-alpine:3
          context: ./alpine-3
          file: ./alpine-3/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_3.outputs.digest }}
