name: debian-docker-images

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '* * 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Debian Buster
        id: docker_build_buster
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-debian:buster
          context: ./debian-buster
          file: ./debian-buster/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_buster.outputs.digest }}
      - name: Build and push Debian Stretch
        id: docker_build_stretch
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-debian:stretch
          context: ./debian-stretch
          file: ./debian-stretch/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_stretch.outputs.digest }}
      - name: Build and push Debian Jessie
        id: docker_build_jessie
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-debian:jessie
          context: ./debian-jessie
          file: ./debian-jessie/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_jessie.outputs.digest }}
      - name: Build and push Debian Latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-debian:latest
          context: ./debian
          file: ./debian/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
