name: fedora-docker-images

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 7 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Fedora Latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-fedora:latest
          context: ./fedora
          file: ./fedora/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
