name: ubuntu-docker-images

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 6 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Ubuntu Trusty
        id: docker_build_trusty
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-ubuntu:trusty
          context: ./ubuntu-trusty
          file: ./ubuntu-trusty/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_trusty.outputs.digest }}
      - name: Build and push Ubuntu Xenial
        id: docker_build_xenial
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-ubuntu:xenial
          context: ./ubuntu-xenial
          file: ./ubuntu-xenial/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_xenial.outputs.digest }}
      - name: Build and push Ubuntu Bionic
        id: docker_build_bionic
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-ubuntu:bionic
          context: ./ubuntu-bionic
          file: ./ubuntu-bionic/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_bionic.outputs.digest }}
      - name: Build and push Ubuntu Focal
        id: docker_build_focal
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-ubuntu:focal
          context: ./ubuntu-focal
          file: ./ubuntu-focal/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_focal.outputs.digest }}
      - name: Build and push Ubuntu Latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joelnb/dumb-init-ubuntu:latest
          context: ./ubuntu
          file: ./ubuntu/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
